name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Build with Buildozer
        run: |
          # Aceptar licencias de Android automáticamente
          yes | buildozer android debug
