name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Create RAM Swap (Memoria Extra)
        run: |
          sudo swapoff -a
          sudo dd if=/dev/zero of=/swapfile bs=1M count=6144
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade Cython==0.29.33 virtualenv buildozer

      - name: Build with Buildozer
        run: |
          rm -rf ~/.buildozer
          export GRADLE_OPTS="-Xmx4g -XX:MaxMetaspaceSize=1g"
          export P4A_EXTRA_CFLAGS="-O0 -DHB_NO_MT -DHB_NO_OT_SHAPER_ARABIC -DHB_NO_OT_SHAPER_KHMER -DHB_NO_OT_SHAPER_MYANMAR -DHB_NO_OT_SHAPER_THAI"
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DreamTone-Final
          path: bin/*.apk
